import type { ProgramStep, StepResult } from "@/lib/types";
import { programToLines, COMMENTS } from "@/lib/program";

const Check = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>
);

export default function ProgramPanel({
  program, steps, current,
}: { program: ProgramStep[]; steps: StepResult[]; current: number }) {
  const lines = programToLines(program);

  return (
    <section className="panel program" aria-label="Program — AI reasoning">
      <div className="panel-head">
        <div className="panel-title">Program <span className="sub">(AI reasoning)</span></div>
        <div className="panel-meta">visual_program.py</div>
      </div>
      <div className="code">
        <div className="preamble"># compiled by the model from the question</div>
        {program.map((s, i) => {
          const cls = i === current ? "active" : i < current ? "done" : "pending";
          const empty = steps[i]?.status === "empty";
          return (
            <div className={`step-block ${cls}`} key={s.id}>
              <div className="comment">
                <span className="mk" style={{ color: empty ? "var(--muted)" : "var(--green)" }}>
                  {i < current ? (empty ? "○" : <Check />) : i === current ? "▸" : ""}
                </span>
                {COMMENTS[s.op] ?? `# ${s.op}`}
              </div>
              <div className="code-line">
                {lines[i].map((tok, j) => (
                  <span key={j} className={tok.c}>{tok.t}</span>
                ))}
              </div>
            </div>
          );
        })}
      </div>
      <div className="code-foot">
        generated by <b>program-gen · llm</b> → executed on Azure AI Vision primitives
      </div>
    </section>
  );
}
